[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install", "cd backend && npm install", "cd ../frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && npm run db:migrate && npm run db:seed && NODE_ENV=production npm start"
