[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm install && cd ../frontend && npm install']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd backend && node src/index.js'
